### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shurshilov** [vladmandic/anti-spoofing#2]
Why I get
Uncaught (in promise) Error: The shape of dict['conv2d_input'] provided in model.execute(dict) must be [-1,128,128,3], but was [192,192,3]
when call
        antiSpoofingCheck: async function(image){
            // init tensorflow
            // await this.parent.human.tf.enableProdMode();
            // await this.parent.human.tf.setBackend('webgl');
            // await this.parent.human.tf.ENV.set('DEBUG', false);
            // await this.parent.human.tf.ready();

            // load model
            const model = await this.parent.human.tf.loadGraphModel('/hr_attendance_face_recognition_pro/static/src/js/models/anti-spoofing.json');

            // run actual prediction
            const res = model.execute(image, ['activation_4']);

            // print results
            // @ts-ignore
            const real = res.dataSync()[0] === 1;
            return real
        },

**Comment by shurshilov** [comment]
Its output from human.js;)
And also if i connect human.js not esm i need new Human.Human(conf) not new Human() I think many people stuck on this step of your library))

**Comment by vladmandic** [comment]
> const real = res.dataSync()[0] === 1;

This is never going to be exactly 1. Treat it as percentage with range 0..1 instead.

**Comment by shurshilov** [comment]
> > const real = res.dataSync()[0] === 1;
> 
> This is never going to be exactly 1. Treat it as percentage with range 0..1 instead.
> 
> > And also if i connect human.js not esm i need new Human.Human(conf) not new Human()
> 
> All depends how you're importing the library. Old IIFE format is exactly that - immediately executed to register as global namespace. But it doesn't have `default` property like ESM does.

Thank you! Its really work!!!

I tested and think 0.70 scale good ? what you think about it?

**Comment by vladmandic** [comment]
0.7 seems reasonable :)
